### ISSUE TITLE
Can't find a way to implement encryptMessage function

### ISSUE THREAD

**Issue by Pavel418** [ZetyByte/ClipSync#14]
https://github.com/ZetyByte/ClipSync/blob/9aeb71d55b11f53e3031835c3b11f9a5e9a1c1ad/server/client.go#L204

some implementations fail to import the key, others give invalid result that the client can't decrypt.

The key is stored as an object in the client and to send it as a string, it has to be exported in one of the formats (SPKI).
The client uses exportKey function from SubtleCrypto library and then it uses importKey function when receiving the key.
But it seems that there is no alternatives to it in golang.

https://github.com/ZetyByte/ClipSync/blob/9aeb71d55b11f53e3031835c3b11f9a5e9a1c1ad/server/client.go#L173
i am also using exact id for testing purposes instead of generating new one each time.

**Comment by Grustamli** [comment]
Why do you need to encrypt a message in the backend?
We discussed that the encryption for now only happens on clients.
Public keys are just transferred from client to server then server to the other client.

I hope I understood correctly that you are trying to encrypt a message on the server.

**Comment by Pavel418** [comment]
i need to encrypt the client's id that is generated in the server. in other case it can be stolen and used by a third person to connect to the client.

**Comment by alik-r** [comment]
@Pavel418 thanks for bringing up the concern about encrypting the client's ID on the server. 
I understand the concern about stolen IDs and the security issue it could create. However, I believe that implementing encryption again on the backend may not be necessary. Instead, by utilizing TLS and the wss:// for client-server communication, we can ensure secure and encrypted connections and prevent eavesdropping for IDs. 
TLS provides encryption and authentication, while WebSockets over wss:// employs the same secure mechanisms as HTTPS. Therefore, I propose leveraging the existing secure protocols rather than adding encryption on the backend.

**Comment by Grustamli** [comment]
@Pavel418 , Indeed stolen id is the least concern since the encryption is already  being done by TLS. We only do E2E encryption on clients to give the users confidence that server can't see the actual payloads. 
We should delay this to a time when we actually analyze the attack vectors for possible ID theft.
Additionally, even if the ID Is stolen, no attacker should be able to access the prior transmissions. It would just create a blank pair.
Hope I could explain it.

**Comment by Pavel418** [comment]
Okay, it is clear.

**Comment by Grustamli** [comment]
I'm closing the issue. Feel free to open it later if needed.
